name: Plan

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform init
        run: terraform init
      
      - id: Apply
        run: terraform apply -auto-approve -no-color
      
      - name: Output
        run: echo ${{ steps.apply.outputs.stdout }}
      
      - name: Errors
        run: echo ${{ steps.apply.outputs.stderr }}
      
      - name: Exit Code
        run: echo ${{ steps.apply.outputs.exitcode }}
