name: Plan

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  apply:
    name: Apply
    runs-on: self-hosted
    env:
      TF_VAR_AWS_ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY }}
      TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      TF_VAR_STACK_NAME: ${{ vars.STACK_NAME }}
      TF_VAR_KUBE_CONTEXT: ${{ vars.KUBE_CONTEXT }}
      TF_VAR_KUBE_CONFIG_PATH: ${{ vars.KUBE_CONFIG_PATH }}
    steps:
      - name: start minikube
        id: minikube
        uses: medyagh/setup-minikube@master

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform init
        run: terraform init
      
      - id: Apply
        run: terraform apply -auto-approve -no-color
