name: Plan

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    env:
      TF_VAR_AWS_ACCESS_KEY: ${{ vars.AWS_ACCESS_KEY }}
      TF_VAR_AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_AWS_REGION: ${{ vars.AWS_REGION }}
      TF_VAR_S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
      TF_VAR_STACK_NAME: ${{ vars.STACK_NAME }}
      TF_VAR_KUBE_CONTEXT: ${{ vars.KUBE_CONTEXT }}
      TF_VAR_KUBE_CONFIG_PATH: ${{ vars.KUBE_CONFIG_PATH }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt check
        run: terraform fmt -check
      
      - name: Terraform init
        run: terraform init
      
      - name: Plan
        run: terraform plan -no-color
